### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by amuramoto**
- Fixed missing org in queryEntityConnectionsAsync
- Added support for retrieving connections by name to queryEntityConnectionsAsync and queryEntityConnections
  -Fixed bug where disconnectEntitiesAsync was calling connectEntities
- Added support for disconnecting connections by name to disconnectEntities and disconnectEntitiesAsync

### CODE REVIEW

**Comment by theganyo** [comment]
Has this been tested and verified? Asking because it looks like the following methods potentially have the same issue:

queryUsersAsync() // (both methods)
queryUsersForGroupAsync()

**Comment by amuramoto** [comment]
I have called the method using the template app and verified it works as expected.

Does appear to be the case for the other methods mentioned. I'll fix, test and send a PR on those.

**Comment by theganyo** [comment]
Are you just updating this PR or sending a new one?

**Comment by amuramoto** [comment]
I can just update this one. Should be done in the next couple hours.

**Pull request merged**
