### PR TITLE
Fix and test for USERGRID-49

### PR DESCRIPTION
**Pull request by aweeraman**
This is a fix and associated test for USERGRID-49.

### CODE REVIEW

**Comment by zznate** [comment]
LGTM - thanks for the test case as well .

**Comment by aweeraman** [comment]
Thanks, that was fast.

**Comment by zznate** [comment]
You caught me at that sweet spot: just after I finished cleaning out my inbox and right before I got started on the day job :)

**Comment by aweeraman** [comment]
Happy coincidence :)

**Pull request merged**
