### PR TITLE
Usergrid 182 properties consolidation

### PR DESCRIPTION
**Pull request by GERey**
Removed the dual configuration files , and merged them into one.

### CODE REVIEW

**Comment by tnine** [comment]
Dumb question, but why the new property file name?  Is it possible to keep the old property file name so it's less administration for our users to change to the new persistence?

**Comment by GERey** [comment]
It's possible. I only used the corepersistence.properties because we're using the new corepersistence stuff. @snoopdave any thoughts on this? Should be a trivial change.

**Comment by zznate** [comment]
That needs to stay the same. That would be exactly the type of thing that could get overlooked when deploying an update via automation tools.

**Comment by GERey** [comment]
Alright, I'll update the properties to use the default. Thanks guys!

**Pull request closed without merging**
