### PR TITLE
USERGRID-2 package namespace to org.apache.usergrid

### PR DESCRIPTION
**Pull request by lewismc**
OK folks, here is a first shot attempt at addressing the above issue.
Stack is running fine for me locally. Test seem to be passing fine (still testing).
I've set about renaming some of the sdk packages as well however there is more work to be done here.
I've updated pom's where I saw fit, however more attention should be paid to defining accurate entries for pom files in another issue.

As expected, this pull request is a beast... however unfortunately unless we go on a module-by-module basis, there is no easy way to do this.

### CODE REVIEW

**Comment by lewismc** [comment]
I saw a whole bunch of commits go through for this one. Did Dave commit this to master branch?

**Comment by ghost** [comment]
It seems we cannot automatic merge. Could you merge from UG master? Thanks.

**Comment by lewismc** [comment]
The changes I've made in this pull request are to master branch. Everything has been merged and AFAICT the pull request is in sync with master branch.

**Comment by ghost** [comment]
Odd the "Merge pull request" button just turned green just now: my bad. This is huge as you said so we better do some serious testing on this. It's going to take some time unfortunately ... please forgive any delays.

**Comment by lewismc** [comment]
No probs. I DID have some build errors on my side so I am not sure if these are only on my local environment or if the package renaming is the issue. We will find out soon enough. 
I'm looking in to how the SDK's need to comply with package renaming as well. I'll write back here in due course. Thanks

**Comment by snoopdave** [comment]
I'm going to take a closer look at this today.

**Comment by lewismc** [comment]
Nice Dave.
I've also been over on general@incubator regarding naming conventions for
non-Java-based packages.
http://www.mail-archive.com/general%40incubator.apache.org/msg43049.html
If you guys have any comments/proposals for how we name the JDK's then I'll
be happy to implement.
Ta
Lewis

On Mon, Feb 3, 2014 at 7:53 PM, Dave Johnson notifications@github.comwrote:

> I'm going to take a closer look at this today.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/usergrid/usergrid/pull/39#issuecomment-33992916
> .

## 

_Lewis_

**Comment by snoopdave** [comment]
@lewismc Thanks so much for undertaking this huge chunk of work. I've cloned your repo and am reviewing the changes. I can't get the stack to compile properly due to what looks like a failed merge and some Maven dependency problems. I'm going to try to work through them and get back to you with my changes.

**Comment by snoopdave** [comment]
I'm still working on this and hope to have a PR ready later today.

**Comment by lewismc** [comment]
No probs Dave.
Great effort.

On Tue, Feb 4, 2014 at 3:36 PM, Dave Johnson notifications@github.comwrote:

> I'm still working on this and hope to have a PR ready later today.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/usergrid/usergrid/pull/39#issuecomment-34071453
> .

## 

_Lewis_

**Comment by snoopdave** [comment]
@lewismc this has turned into a huge amount of work due to the fact that we use the Usergrid Java SDK in the REST module tests and the SDK depends on a newer version of Jackson. I bit the bullet and did the over 300 edits necessary to use the new Jackson API, but I am still fighting a half-dozen failing tests.

I would like to close the PR and continue this work in the package-rename branch, which is based on the code from your PR plus my changes. We can both work directly out of that branch until we are ready to submit a PR to get it merged into master. Sound OK?

**Comment by lewismc** [comment]
Sounds dynamite Dave.
i think sharing the work is a muchbetter solution. I really just wanted to
kick this one off so need to thank you for stepping up and taking it on.
This is very rarely an easy issue to deal with for new podlings.

On Thu, Feb 6, 2014 at 3:17 PM, Dave Johnson notifications@github.comwrote:

> @lewismc https://github.com/lewismc this has turned into a huge amount
> of work due to the fact that we use the Usergrid Java SDK in the REST
> module tests and the SDK depends on a newer version of Jackson. I bit the
> bullet and did the over 300 edits necessary to use the new Jackson API, but
> I am still fighting a half-dozen failing tests.
> 
> I would like to close the PR and continue this work in the package-rename
> branch, which is based on the code from your PR plus my changes. We can
> both work directly out of that branch until we are ready to submit a PR to
> get it merged into master. Sound OK?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/usergrid/usergrid/pull/39#issuecomment-34332798
> .

## 

_Lewis_

**Comment by snoopdave** [comment]
I think I'm going to defer the Jackson and Jersey upgrade and abandon the edits that I made.

Instead of doing the upgrade, I've added a local repo to Usergrid with the old Java client (0.0.3) dependency. That way we can do the package rename independently from the Jackson upgrade. 

We can do the Jackson upgrade in a later PR.

**Comment by lewismc** [comment]
In all honesty Dava,. this is why I logged the jackso0n upgrade but never
started it. I see them as different (linked) issues.
I found myself changing jackson dependencies in pom.xml and thinking I had
just opened a huge can of worms.
If you can write your view point on what needs to be done to address the
package renaming then I'll chip in where I can to get this one done and
dusted.

On Thu, Feb 6, 2014 at 8:05 PM, Dave Johnson notifications@github.comwrote:

> I think I'm going to defer the Jackson and Jersey upgrade and abandon the
> edits that I made.
> 
> Instead of doing the upgrade, I've added a local repo to Usergrid with the
> old Java client (0.0.3) dependency. That way we can do the package rename
> independently from the Jackson upgrade.
> 
> We can do the Jackson upgrade in a later PR.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/usergrid/usergrid/pull/39#issuecomment-34364672
> .

## 

_Lewis_

**Comment by zznate** [comment]
I'd like to have @edanuff chime in here - he had this all working at one point, but we had to back it out (begrudgingly) due to a merge conflict with a critical feature fix.

**Comment by edanuff** [comment]
It was all working but there were a few problems that were seen when we ran it in Tomcat that didn't show up in the unit tests.  It was also a major pain and touched 22 files although this was mostly hunting down every org.codehaus.jackson.\* import and replacing it with com.fasterxml.jackson.\* equivalents.  This was all inside the pull request for Usergrid-348 "JSON Schema Support for Entity Types"

**Comment by snoopdave** [comment]
The new package-rename branch is here and 100% of stack tests are now passing:
https://github.com/usergrid/usergrid/tree/package-rename-only

I'm going to close the PR and will continue this work in that branch.

**Comment by lewismc** [comment]
Thanks Dave

On Fri, Feb 7, 2014 at 2:12 AM, Dave Johnson notifications@github.comwrote:

> Closed #39 https://github.com/usergrid/usergrid/pull/39.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/usergrid/usergrid/pull/39
> .

## 

_Lewis_

**Comment by lewismc** [comment]
Do we have any clear understanding of
1) What still needs to be renamed
2) The naming format for packages other than Java-based?

On Fri, Feb 7, 2014 at 10:32 AM, Lewis John Mcgibbney <
lewis.mcgibbney@gmail.com> wrote:

> Thanks Dave
> 
> On Fri, Feb 7, 2014 at 2:12 AM, Dave Johnson notifications@github.comwrote:
> 
> > Closed #39 https://github.com/usergrid/usergrid/pull/39.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/usergrid/usergrid/pull/39
> > .
> 
> ## 
> 
> _Lewis_

## 

_Lewis_

**Comment by snoopdave** [comment]
1. the Java and Android SDKs still need to be renamed.
2. I don't believe that Portal and other SDKs need any package renaming because none of them use domain names as part of package names (i.e. none use "org.usergrid"). They do use "Usergrid" and I don't believe that we have to prefix every occurrence of Usergrid with Apache.

**Comment by lewismc** [comment]
Hi Dave,

**Pull request closed without merging**
