### PR TITLE
Package rename only

### PR DESCRIPTION
**Pull request by snoopdave**
Here's what I've done in this branch:
1. Used Netbeans refactoring tools to rename all Stack, Java and Android SDK packages from org.usergrid to org.apache.usergrid
2. In the Stack, Java and Android SDK modules, did a global replace of org.usergrid with org.apache.usergrid, and of org/usergrid with org/apache/usergrid.
3. In the REST module, added the old Usergrid Java SDK 0.0.3 jars in a local Maven module so we don't have to upgrade Jackson as part of the rename. In the Android SDK module, added the old Usergrid Java SDK 0.0.6 jars because that is the version it depends on.
4. Regenerated the Javadoc API docs for both the Java and Android SDKs.
5. Downgraded from Recaptcha 0.0.8 to 0.0.7 because the former is not in Maven Central. Also, downgraded from AppleJavaExtensions 1.5 to 1.4 for the same reason.
6. I upped the version numbers to:
   
   Stack        0.0.29-SNAPSHOT
   Java SDK     0.0.9-SNAPSHOT
   Android SDK  0.0.7-SNAPSHOT

All Stack tests are now passing and I think this is ready for master. We still need to get rid of those local jars and upgrade the newer versions of Jackson (and Jersey) but that is a (huge) task for another day.

This work is for https://issues.apache.org/jira/browse/USERGRID-2

### CODE REVIEW

**Comment by ghost** [comment]
This is looking great!

**Comment by snoopdave** [comment]
Please hold off on merging this PR, I think I just found a launcher issue.

Also, I'd like to give people time for feedback since this is such a biggie.

**Comment by zznate** [comment]
Does it make sense to split off b5d399b - I feel like that is the long pole in the tent in terms of surface area for folks working on other stuff.

**Comment by snoopdave** [comment]
@zznate what would the benefit of splitting out the Stack vs. SDK changes here?

**Comment by zznate** [comment]
Thinking strictly in terms of blocking - it seems like a couple of the folks over the horizon were in the midst of a couple of things. If you feel like you can clean up the launcher issue quickly than no worries.

**Comment by zznate** [comment]
@snoopdave just noticed the reference to USERGRID-2 - big "never mind" as these two issues def. takes priority, IMO.

**Comment by snoopdave** [comment]
OK, launcher now works and I believe this PR is ready to merge.

**Comment by sungjuly** [comment]
@snoopdave Great job!

**Comment by zznate** [comment]
From a clean checkout of the github repo with this branch:
- compiled 
- tests pass
- launcher works (with and w/o GUI)

I have a merge conflict with the work @stliu did with for USERGRID-77 (f564f0) . I'm going to see if I can straighten that out.

**Comment by zznate** [comment]
Word!

**Pull request merged**
