### PR TITLE
removing dynamic_property when value is empty

### PR DESCRIPTION
**Pull request by PahanPerera**
This changes remove the dynamic property when the corresponding value for that property is empty. 
Bug Fixing for https://issues.apache.org/jira/browse/USERGRID-21

### CODE REVIEW

**Comment by malakaM** [comment]
@PahanPerera , 

I think this fixes two issues on JIRA?...if so I suggest you put both defect IDs here for review by the commiters.

Thanks, 
Malaka

**Comment by tnine** [comment]
LGTM, can you link the issues so we can close them?

Thanks!

**Comment by PahanPerera** [comment]
Hi, issues are 

1) https://issues.apache.org/jira/browse/USERGRID-21
2) https://issues.apache.org/jira/browse/USERGRID-97

Thanks !

**Comment by rodsimpson** [comment]
Thanks guys!!

**Pull request merged**
