### PR TITLE
Miscellaneous changes

### PR DESCRIPTION
**Pull request by stliu**
Miscellaneous changes, only some code refactoring  and change the enforcer rule to allow maven 3.1.1, all tests pass

### CODE REVIEW

**Comment by tnine** [comment]
Hey man.  Sorry this hasn't been reviewed yet, I'm swamped at the moment, I'm hoping to get to it some time this weekend.

**Comment by tnine** [comment]
Hey Strong,
  Can you update this PR to work with the latest master?  Also, if you could, can you remove the import changes, and we'll tackle that later?  We're going to add a checkstyle plugin to maven that ensures we all follow the same formatting and import rules.  Until then, I think we should avoid changes like the imports and braces to keep our change sets clearer.

**Comment by stliu** [comment]
updated as request, thanks

**Comment by tnine** [comment]
Thanks man.  I need to manually merge/check this since Jenkins isn't set up for this yet.  I've scheduled some time to get to it on Monday.

**Comment by tnine** [comment]
Would it be possible to merge/rebase this onto the package rename?

**Comment by snoopdave** [comment]
@stliu I'm curious. What tool did you use to make the "miscellaneous" changes?

**Comment by stliu** [comment]
sorry for the late response, I just pushed a new commit which rebased to the latest master, so it can be merged fast forward

I'm using Intellij, it has a very cool code inspection tool, which can find some bad smell code and do quick fix, but mostly, I do mirror code refactor during read the code and combine them together

**Comment by stliu** [comment]
anyone is going to take a look of this or shall i just go head and merge it by myself?

**Pull request merged**
